services:
  - type: web
    name: aura-smart-dining
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
