services:
  - type: web
    name: aura-smart-dining
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps --include=dev && cd client && npm install --legacy-peer-deps --include=dev && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 686445090372-17hhr1l6fsbjots3e8kuse904cv9rq72.apps.googleusercontent.com
